### ISSUE TITLE
Integer 9223372036854775808 is no longer rejected by simdjson

### ISSUE THREAD

**Issue by lemire** [erthalion/pg_simdjson#1]
```
$ ./json2json -d test.json 
0 : r   // pointing to 3 (right after last node)
1 : unsigned integer 9223372036854775808
3 : r   // pointing to 0 (start root)
```

**Comment by lemire** [comment]
That is, we support unsigned 64-bit integers...

**Comment by erthalion** [comment]
Thanks, I'll take a look. Could be that I'm using too old version (actually I've created this extension some time ago, and just published recently).

**Comment by erthalion** [comment]
I've updated version of standalone simdjson (see 4e5a20eab6296d48), and indeed now uint64 are supported.
