### ISSUE TITLE
Performance numbers are improbable

### ISSUE THREAD

**Issue by lemire** [erthalion/pg_simdjson#2]
If the plot is meant to refer to a JSON parsing tests, then something is off. The README plot seems to indicate that you can parse 320 kB in 7 ms. Or 0.32 MB in 0.007 s... or 45 MB/s. I don't think it is possible for simdjson to run that slowly, and very few parsers are that slow.

**Comment by erthalion** [comment]
Oh, I see the source of confusion. The README plot is not just pure parsing, this 7ms includes everything, basically all overhead one needs to have to perform a query (I wanted to see how the extension would behave in a situation relatively close to a real use case). I still have to break this timeframe down to see how long takes every part, but if we will take a look at only simdjson part, seems like it's time distribution is strongly between 256 - 511 microseconds:

```
$ funclatency -u pg_simdjson.so:_ZN8simdjson17build_parsed_jsonEPKhmb
Tracing 1 functions for "pg_simdjson.so:_ZN8simdjson17build_parsed_jsonEPKhmb"... 
 
    usecs               : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 0        |                                        |
         4 -> 7          : 0        |                                        |
         8 -> 15         : 0        |                                        |
        16 -> 31         : 0        |                                        |
        32 -> 63         : 0        |                                        |
        64 -> 127        : 0        |                                        |
       128 -> 255        : 0        |                                        |
       256 -> 511        : 10015    |****************************************|
       512 -> 1023       : 1        |                                        |
```

Based on your calculations it's about 1.3 GB/s, which should be closer to the correct numbers, right?

I'll update the README to state this more clearly.

**Comment by lemire** [comment]
Yes, 1.3 GB/s is credible!

**Comment by erthalion** [comment]
I've updated the README, hope it's more clear now.

Btw, thanks a lot for simdjson, I enjoyed reading "Parsing Gigabytes of JSON per Second" article!

**Comment by lemire** [comment]
Thanks for your work.

I am hoping it will entice folks to look into it.
